server:
  port: 8080

spring:
  #  activemq:
  #    enabled: true
  #    in-memory: true # Use an embedded, in-memory broker
  #    broker-url: "vm://localhost?broker.persistent=false" # Ensure messages are not persisted on disk
  #    packages:
  #      trust-all: true # For trusting our own model packages for ObjectMessage, though JSON is often better
  #    pool:
  #      enabled: true
  #      max-connections: 10
  artemis:
    mode: embedded
    embedded:
      enabled: true
      persistent: false
    broker-url: "vm://0?broker.persistent=false"
  jms:
    pub-sub-domain: true # Default to topics for listeners unless overridden in factory
    cache:
      enabled: true

app:
  # Configuration for JMS destinations
  jms:
    # Raw ticks are now topics to allow multiple services (Aggregator, PriceStreamService) to consume them
    topics:
      rawTicksHighActivity: "RAW_TICKS_TOPIC.HIGH_ACTIVITY"
      rawTicksMediumActivity: "RAW_TICKS_TOPIC.MEDIUM_ACTIVITY"
      rawTicksLowActivity: "RAW_TICKS_TOPIC.LOW_ACTIVITY"
      aggregatedUpdates: "AGGREGATED_LH_STOCK_UPDATES_TOPIC"

    # Configuration for the Mock Tick Producer
  mockProducer:
    enabled: true
    # Stock categories mapping. This drives which topic the ticks are sent to.
    stockCategories:
      HIGH_ACTIVITY: [ "RELIANCE", "HDFCBANK", "ICICIBANK" ]
      MEDIUM_ACTIVITY: [ "INFY", "TCS", "SBIN", "KOTAKBANK" ]
      LOW_ACTIVITY: [ "WIPRO", "ASIANPAINT", "NESTLEIND" ]
      # Price simulation parameters
    tickVolatility: 0.005 # 0.5%
    driftUpdateTicks: 1000 # Change drift bias every 1000 ticks
    driftBiasRange: 0.1 # New drift bias will be between -0.1 and +0.1
    # Throughput control per category
    frequencyMillis:
      HIGH_ACTIVITY: 50   # ~20 ticks/sec
      MEDIUM_ACTIVITY: 100 # ~10 ticks/sec
      LOW_ACTIVITY: 500  # ~2 ticks/sec

    # Configuration for the Window Aggregator
  windowAggregator:
    enabled: true
    timerCheckIntervalMillis: 50 # How often to check for closable windows
    # Window durations per category
    windowDurationMillis:
      HIGH_ACTIVITY: 250
      MEDIUM_ACTIVITY: 500
      LOW_ACTIVITY: 1000
      # Concurrency settings for JMS listeners per category
    listenerConcurrency:
      HIGH_ACTIVITY: "5-10"
      MEDIUM_ACTIVITY: "3-8"
      LOW_ACTIVITY: "1-5"

logging:
  level:
    # Suppress Artemis logs
    org.apache.activemq.audit: ERROR
    org.apache.activemq.artemis: WARN